site_name: COMPASS CTF Wiki
site_url: https://wiki.compass.college
repo_name: lyther/wiki
repo_url: https://github.com/lyther/wiki
site_description: Wiki project for COMPASS CTF, for usage of information sharing, collection, and reference. The contents are contributed by the students of COMPASS CTF team.
copyright: COMPASS & SUSTech 2021 CTF team

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  palette:
    primary: white
    accent: cyan
    scheme: preference
  icon:
    logo: logo
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  plugins:
  - search
  - minify:
    minify_html: true

nav:
- Abstract:
  - index.md
- Book:
  - Computer and System:
    - Book/Computer and System/Android Dalvik虚拟机结构及机制剖析.md
    - Book/Computer and System/Android Internals.md
    - Book/Computer and System/Android系统源代码情景分析.md
    - Book/Computer and System/Code.md
    - Book/Computer and System/Computer Systems.md
    - Book/Computer and System/Linux Kernel Development.md
    - Book/Computer and System/Mac OS X and iOS Internals.md
    - Book/Computer and System/Understanding the Linux Kernel.md
    - Book/Computer and System/Windows Internals.md
    - Book/Computer and System/代码揭秘.md
    - Book/Computer and System/深入理解Android内核设计思想.md
  - Cryptography:
    - Book/Cryptography/Foundations of Cryptography.md
    - Book/Cryptography/Introduction to Modern Cryptography.md
    - Book/Cryptography/Understanding Cryptography.md
    - Book/Cryptography/图解密码技术.md
  - Network:
    - Book/Network/Computer Networking.md
    - Book/Network/Practical Packet Analysis.md
    - Book/Network/TCP IP Illustrated.md
  - Programming:
    - C:
      - Book/Programming/C/C Primer Plus.md
      - Book/Programming/C/C Programming Language.md
      - Book/Programming/C/C Traps and Pitfalls.md
      - Book/Programming/C/Expert C Programming Deep C Secrets.md
      - Book/Programming/C/Pointers on C.md
    - C++:
      - Book/Programming/C++/C++ Primer Plus.md
      - Book/Programming/C++/C++ Primer.md
  - PWN:
    - Book/PWN/Practical Malware Analysis.md
    - Book/PWN/加密与解密.md
    - Book/PWN/逆向工程核心原理.md
  - Security:
    - Book/Security/0day安全.md
    - Book/Security/A Guide to Kernel Exploitation.md
    - Book/Security/Fuzzing for Software Security Testing and Quality Assurance.md
    - Book/Security/Gray Hat Hacking.md
    - Book/Security/Rootkit.md
    - Book/Security/漏洞战争.md
- CS315:
  - CS315/Overview.md
  - CS315/Week 1.md
  - CS315/Week 2.md
  - CS315/Week 3.md
  - CS315/Week 4.md
  - CS315/Week 5.md
  - CS315/Week 6.md
  - CS315/Week 7.md
  - CS315/Week 8.md
  - CS315/Week 9.md
  - CS315/Week 10.md
  - CS315/Week 11.md
  - CS315/Week 12.md
  - CS315/Week 13.md
  - CS315/Week 14.md
  - CS315/Exercise Solutions.md
- Paper:
  - Artificial Intelligence:
    - Paper/Artificial Intelligence/Cert-RNN Towards Certifying the Robustness of Recurrent.md
    - Paper/Artificial Intelligence/Unleashing the Tiger Inference Attacks on Split Learning.md
  - Cryptography:
    - Paper/Cryptography/Fuzzy Message Detection.md
    - Paper/Cryptography/Key Agreement for Decentralized Secure Group Messaging with Strong Security Guarantees.md
  - Internet of Things:
    - Paper/Internet of Things/Snipuzz Black-box Fuzzing of IoT Firmware via Message Snippet Inference.md
  - Misc:
    - Paper/Misc/Chaff Bugs Deterring Attackers by Making Software Buggier.md
  - Mobile:
    - Paper/Mobile/Consistency Analysis of Data-Usage Purposes in Mobile Apps.md
  - PWN:
    - Paper/PWN/Exorcising Spectres with Secure Compilers.md
    - Paper/PWN/Preventing Dynamic Library Compromise on Node.js via RWX-Based Privilege Reduction.md
  - Reverse Engineering:
    - Paper/Reverse Engineering/Search-based Approaches for Local Black-Box Code Deobfuscation Understand, Improve and Mitigate.md
- Tool:
  - Cryptography:
    - Tool/Cryptography/SageMathCell.md
  - PWN:
    - Tool/PWN/IDA.md
    - Tool/PWN/PEiD.md
    - Tool/PWN/WinDbg.md
    - Tool/PWN/WinHex.md
    - Tool/PWN/x64dbg.md
  - Reverse Engineering:
    - Tool/Reverse Engineering/Bytecode Viewer.md
    - Tool/Reverse Engineering/DiE.md
    - Tool/Reverse Engineering/ExeInfoPE.md
- Tutorial:
  - Material:
    - Tutorial/Material/Binary Exploitation.md
    - Tutorial/Material/Cryptography.md
    - Tutorial/Material/Network.md
    - Tutorial/Material/OS.md
    - Tutorial/Material/Penetration.md
    - Tutorial/Material/Reverse.md
  - Schedule:
    - Tutorial/Schedule/Summer.md
    - Tutorial/Schedule/2021Fall.md
- Website:
  - Forum:
    - Website/Forum/kanxue.md
  - Platform:
    - Website/Platform/Cryptopals.md
    - Website/Platform/CTFHub.md
    - Website/Platform/CTFlearn.md
    - Website/Platform/ctftime.md
    - Website/Platform/ichunqiu.md
    - Website/Platform/picoCTF.md
    - Website/Platform/pwnabletw.md
    - Website/Platform/TryHackMe.md
    - Website/Platform/World of Attack&Defense.md
  - Tutorial:
    - Website/Tutorial/CTF Field Guide.md
    - Website/Tutorial/CTF Wiki.md
    - Website/Tutorial/ctf101.md
    - Website/Tutorial/how to become a hacker.md
    - Website/Tutorial/linux.md
    - Website/Tutorial/python.md
- Writeup:
  - Binary Exploitation:
    - Writeup/Binary Exploitation/beginner-generic-pwn-number-0.md
    - Writeup/Binary Exploitation/collision.md
    - Writeup/Binary Exploitation/fd.md
    - Writeup/Binary Exploitation/printf-please.md
    - Writeup/Binary Exploitation/ret2generic-flag-reader.md
    - Writeup/Binary Exploitation/ret2the-unknown.md
    - Writeup/Binary Exploitation/simultaneity.md
  - Cryptography:
    - Writeup/Cryptography/blowfishgame.md
    - Writeup/Cryptography/Dachshund Attacks.md
    - Writeup/Cryptography/Exposure.md
    - Writeup/Cryptography/Guess.md
    - Writeup/Cryptography/MedicalImage.md
    - Writeup/Cryptography/more_calc.md
    - Writeup/Cryptography/myRSA.md
    - Writeup/Cryptography/Random_RSA.md
    - Writeup/Cryptography/RSAssss.md
    - Writeup/Cryptography/scissor.md
    - Writeup/Cryptography/secret share.md
    - Writeup/Cryptography/simpleRSA.md
  - Forensics:
    - Writeup/Forensics/Disk, disk, sleuth! II.md
    - Writeup/Forensics/Disk, disk, sleuth!.md
    - Writeup/Forensics/MacroHard WeakEdge.md
    - Writeup/Forensics/Milkslap.md
    - Writeup/Forensics/Wireshark doo dooo do doo.md
  - General Skills:
    - Writeup/General Skills/2Warm.md
    - Writeup/General Skills/ChieftainsSecret.md
    - Writeup/General Skills/Lets Warm Up.md
    - Writeup/General Skills/shuffle_code.md
    - Writeup/General Skills/xixixi.md
    - Writeup/General Skills/到点了.md
    - Writeup/General Skills/层层取证.md
    - Writeup/General Skills/带音乐家.md
    - Writeup/General Skills/考古.md
    - Writeup/General Skills/进制反转.md
    - Writeup/General Skills/鸣雏恋.md
  - Reverse Engineering:
    - Writeup/Reverse Engineering/apk1.md
    - Writeup/Reverse Engineering/bread-making.md
    - Writeup/Reverse Engineering/dimensionality.md
    - Writeup/Reverse Engineering/re1.md
    - Writeup/Reverse Engineering/Shop.md
    - Writeup/Reverse Engineering/speeds and feeds.md
    - Writeup/Reverse Engineering/wstrings.md
  - Web Exploitation:
    - Writeup/Web Exploitation/Cookies.md
    - Writeup/Web Exploitation/inspect-me.md
    - Writeup/Web Exploitation/It is my Birthday.md
    - Writeup/Web Exploitation/Most Cookies.md
    - Writeup/Web Exploitation/Scavenger Hunt.md
